#!/bin/bash
#
# file:        battery-warn
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: This script warns you when your battery dips below a certain
#              percentage. Requires xmessage and bc.

# Get AC status.
ac_status=$(acpi | awk '{print $3}' | tr -d ',')

# If charging, do nothing and exit.
if [[ $ac_status == "Charging" ]]; then
    exit 0
fi

# Get current percent.
pct_now=$(acpi | awk '{print $4}' | tr -d '%,')

# Percent at which to raise warning.
pct_threshold=5

# If more than $pct_threshold, do nothing and exit.
if [[ $pct_now -gt $pct_threshold ]]; then
    exit 0
fi

# If discharging and at $pct_threshold or below, raise xmessage warning.
DISPLAY=:0 xmessage -buttons okay:0 -center -default okay -print "Low battery: $pct_now%."
