#!/bin/bash
#
# file:        cbr2cbz
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: Converts a cbr (comic book rar) file to cbz (comic book zip)
#              format.

cbr_file=$1
cbz_file="$(basename "${cbr_file}" .cbr).cbz"
start_dir=$(pwd)
temp_dir=$(mktemp -d)

cd "${temp_dir}"
unrar e -inul "${start_dir}/${cbr_file}"
zip -q "${start_dir}/${cbz_file}" *
rm -rf "${temp_dir}"
