#!/bin/bash
#
# file:        check-updates
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: Check for the number of official and AUR updates, and write
#              outputs to two files. Useful for running as an hourly systemd
#              timer/service, then piping the contents to a status bar.

checkupdates       | wc -l > /tmp/checkup-official
aurcheck -d custom | wc -l > /tmp/checkup-aur
