#!/bin/bash
#
# file:        display-adjust
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: If external monitor is present, auto-adjust it and turn off
#              laptop monitor; otherwise, auto-adjust laptop monitor (and turn
#              off external monitor).

if [[ -n "$(xrandr | grep "VGA1 connected")" ]]; then
    xrandr --output VGA1 --auto
    xrandr --output LVDS1 --off
else
    xrandr --output LVDS1 --auto
    xrandr --output VGA1 --off
fi
