#!/bin/bash
#
# file:        display-adjust
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: If external monitor is present, auto-adjust it; otherwise,
#              auto-adjust laptop monitor (and turn off external monitor).

if [[ -n "$(xrandr | grep "HDMI-1 connected")" ]]; then
    xrandr --output HDMI-1 --auto
else
    xrandr --output eDP-1 --auto
    xrandr --output HDMI-1 --off
fi
