#!/usr/bin/env bash
#
# file:        docmenu
# author:      Brian Buccola <brian.buccola@gmail.com>
# description: dmenu script to open a PDF document with MuPDF.

shopt -s nullglob globstar

# Set documents directory.
docs_dir="$HOME/docs"

# Get a list of PDFs, stripping prefix and suffix.
docs=( "$docs_dir"/{books,papers}/*.pdf )
docs=( "${docs[@]#$docs_dir/books/}" )
docs=( "${docs[@]#$docs_dir/papers/}" )
docs=( "${docs[@]%.pdf}" )

# Pass the list to dmenu to select a PDF.
doc=$(printf '%s\n' "${docs[@]}" | dmenu -p doc: "$@")

# If the user cancels dmenu, just exit.
[[ -n "$doc" ]] || exit

# Look for the doc in books, otherwise in papers.
[[ -f "$docs_dir"/books/"$doc".pdf ]] && doc="$docs_dir/books/$doc".pdf || doc="$docs_dir/papers/$doc".pdf

# Open the PDF.
mupdf "$doc"
