#!/bin/bash
#
# file:        keyboard-adjust
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: Set up kbd layouts, and switch caps lock with ctrl_L.

setxkbmap -layout us,de,it,il -variant dvp,,, # programmers-dvorak kbd primary
setxkbmap -option                             # clear options
setxkbmap -option "grp:shifts_toggle"         # use both shifts to toggle layout
setxkbmap -option "ctrl:swapcaps"             # swap ctrl_L and caps lock
