#!/bin/bash
#
# file:        keyboard-adjust
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: Set up kbd layouts, and switch caps lock with ctrl_L.

setxkbmap -layout us -variant dvp # programmers-dvorak kbd primary
setxkbmap -option                 # clear options
setxkbmap -option "ctrl:swapcaps" # swap ctrl_L and caps lock
setxkbmap -option "compose:rctrl" # use ctrl_R as compose key, e.g. for 'e -> é
