#!/bin/bash
#
# file:        manmenu
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: Open man pages with dmenu. (Or replace 'dmenu' with 'rofi -dmenu'
#              to use rofi instead.)

# Get manpages, pipe to dmenu, and prettify.
manpage=$(man -k . | awk '{ print $1 " " $2 }' | dmenu -p man: "$@" | awk '{ print $2 " " $1 }' | tr -d '()')

# If user hits <Esc>, exit.
[[ -n "${manpage}" ]] || exit

# Otherwise, open manpage with st.
st -e man $(echo -n "${manpage}")
