#!/bin/bash
#
# file:        musicsync
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: This script transfers music listed in an m3u playlist, with one
#              song per line and relative paths, from the local machine to an
#              external mp3 player.

src=/mnt/floyd/beets
dest=/mnt/usb/MUSIC
files=$HOME/.mpd/playlists/tmp.m3u
bkupdir=$HOME/.musicsync
log=$bkupdir/log

if [[ ! -d $dest ]]; then
    echo "Error: Destination drive not mounted!"
    exit 0
fi

if [[ ! -d $src ]]; then
    echo "Error: Source drive not mounted!"
    exit 0
fi

if [[ ! -f $files ]]; then
    echo "Error: Cannot find playlist!"
    exit 0
fi

sudo rsync \
    -rvzuhhhP \
    --files-from=$files \
    --log-file=$log \
    $src $dest

exit 0
