#!/bin/bash
#
# file:        pdfgrepdir
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: pdfgrep wrapper that greps all pdfs in given directory for a
#              given pattern

pattern="$1"
dir="$2"

find "$dir" -name "*.pdf" -exec pdfgrep "$pattern" {} +
