#!/bin/bash
#
# file:        slock-toggle
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: Toggle screensaver and screen lock.

if [[ "$#" -gt 0 ]]; then
    if pgrep xautolock &>/dev/null; then
        echo "Screensaver and slock are ON."
    else
        echo "Screensaver and slock are OFF."
    fi
    exit 0
fi

if pgrep xautolock &>/dev/null; then
    pkill xautolock
    xset s off
    xset -dpms
    echo "Screensaver and slock now OFF."
else
    xset s 300 300
    xset +dpms
    xautolock -time 5 -locker slock &
    echo "Screensaver and slock now ON."
fi
