#!/bin/bash
#
# file:        update-notify
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: List how many updates are available. Useful for putting inside a
#              status bar.

ups_official=$(</tmp/checkup-official)
ups_aur=$(</tmp/checkup-aur)
echo "$ups_official($ups_aur)"
