#!/bin/bash
#
# file:        update-notify
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: List how many updates are available. Useful for putting inside a
#              status bar.

official_updates=$(checkupdates | wc -l)
aur_updates=$(cower -uq | wc -l)
echo "Updates: ${official_updates} (${aur_updates})"
