#!/bin/bash
#
# file:        update-notify
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: List how many updates are available. Useful for putting inside a
#              status bar.

official_updates=$(pacman -Qqu --dbpath /tmp/checkup-db-brian | wc -l)
aur_updates=$(</tmp/checkup-aur)
