#!/bin/bash
#
# file:        volmenu
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: Perform some volume actions using dmenu.

# Array of volume actions.
vol_actions=("[m]ute" "[r]eset" "[j]" "[k]" "[h]alf")

# List volume actions (separated by a newline character) and pipe to dmenu.
vol_action=$(echo "${vol_actions[@]}" | tr ' ' '\n' | dmenu -p vol: "$@")

# If user hits <Esc>, exit.
[[ -z "$vol_action" ]] && exit

# Otherwise, perform the volume action.
# For [j], [k], re-run volmenu for easy repeat.
case "$vol_action" in
    "[m]ute") pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
    "[r]eset") pactl set-sink-volume @DEFAULT_SINK@ 100% ;;
    "[j]") pactl set-sink-volume @DEFAULT_SINK@ -5% && "$0" -m 0 -nb "#000000" -nf "#928374" -sb "#000000" -sf "#d3869b" ;;
    "[k]") pactl set-sink-volume @DEFAULT_SINK@ +5% && "$0" -m 0 -nb "#000000" -nf "#928374" -sb "#000000" -sf "#d3869b" ;;
    "[h]alf") pactl set-sink-volume @DEFAULT_SINK@ 50% ;;
esac
