#!/bin/bash
#
# file:        weather
# author:      Brian Buccola <brian.buccola@gmail.com>
#
# description: Print weather information from https://openweathermap.org/.
#
# NB: If you use or adapt this script, please create your own API key.

# First check that we're online. If not, exit with an error code.
interface=$(iwconfig 2>&1 | awk '/^w/ { print $1 }')
wifi_status=$(</sys/class/net/"$interface"/operstate)
[[ "$wifi_status" = "up"   ]] || {
    echo "(no wifi)"
    exit 1
}

# API key. (Use your own!)
api_key="4bbc64162016d9e345436714dd896ecc"

# City,Country.
city_id="Paris,FR"
# city_id="London,CA"
# city_id="New Orleans,US"

# Units and symbol to use.
units="metric"
temp_symbol="°C"

# Get weather info.
weather_url="https://api.openweathermap.org/data/2.5/weather?q=$city_id&appid=$api_key&units=$units"
weather_info=$(wget -qO- "$weather_url")
weather_desc=$(echo "$weather_info" | grep -o -e '\"description\":\"[^\"]*\"' | head -n1 | awk -F ':' '{print $2}' | tr -d '"')
weather_temp=$(echo "$weather_info" | grep -o -e '\"temp\":[^,]*' | awk -F ':' '{print $2}' | tr -d '"')
# Round temperature to nearest whole number.
weather_temp=$(echo "($weather_temp + 0.5) / 1" | bc)

# Print weather description and temperature.
echo "$weather_desc $weather_temp$temp_symbol"
